name:                try-vivid
version:             0.1.0.0
license:             BSD3
author:              "Miguel Negrão"
copyright:           "2021 Miguel Negrão"

#add packages here
dependencies:
- base >= 4.7 && < 5
- vivid

executables:
  try-vivid-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
